-- ============================================================
-- Natural Language Data Analyst — Seed Data
-- ============================================================
-- Inserts ~200 rows of realistic e-commerce dummy data.
-- Run AFTER init_db.sql
-- ============================================================

-- -------------------------------------------------------
-- 1. Users (50 rows)
-- -------------------------------------------------------
INSERT INTO users (name, email, country, created_at) VALUES
('Alice Johnson',      'alice.johnson@email.com',      'United States',  NOW() - INTERVAL '365 days'),
('Bob Martinez',       'bob.martinez@email.com',       'Mexico',         NOW() - INTERVAL '340 days'),
('Clara Schmidt',      'clara.schmidt@email.com',      'Germany',        NOW() - INTERVAL '320 days'),
('David Chen',         'david.chen@email.com',         'China',          NOW() - INTERVAL '300 days'),
('Emily Nakamura',     'emily.nakamura@email.com',     'Japan',          NOW() - INTERVAL '290 days'),
('Fatima Al-Hassan',   'fatima.alhassan@email.com',    'UAE',            NOW() - INTERVAL '280 days'),
('George Williams',    'george.williams@email.com',    'United Kingdom', NOW() - INTERVAL '270 days'),
('Hannah Kim',         'hannah.kim@email.com',         'South Korea',    NOW() - INTERVAL '260 days'),
('Ivan Petrov',        'ivan.petrov@email.com',        'Russia',         NOW() - INTERVAL '250 days'),
('Julia Santos',       'julia.santos@email.com',       'Brazil',         NOW() - INTERVAL '240 days'),
('Kwame Asante',       'kwame.asante@email.com',       'Ghana',          NOW() - INTERVAL '230 days'),
('Laura Rossi',        'laura.rossi@email.com',        'Italy',          NOW() - INTERVAL '220 days'),
('Mohammed Al-Rashid', 'mohammed.alrashid@email.com',  'Saudi Arabia',   NOW() - INTERVAL '210 days'),
('Nadia Kovac',        'nadia.kovac@email.com',        'Croatia',        NOW() - INTERVAL '200 days'),
('Oscar Lindqvist',    'oscar.lindqvist@email.com',    'Sweden',         NOW() - INTERVAL '190 days'),
('Priya Sharma',       'priya.sharma@email.com',       'India',          NOW() - INTERVAL '180 days'),
('Quentin Dubois',     'quentin.dubois@email.com',     'France',         NOW() - INTERVAL '170 days'),
('Rosa Fernandez',     'rosa.fernandez@email.com',     'Spain',          NOW() - INTERVAL '160 days'),
('Samuel Okafor',      'samuel.okafor@email.com',      'Nigeria',        NOW() - INTERVAL '150 days'),
('Tara O''Brien',      'tara.obrien@email.com',        'Ireland',        NOW() - INTERVAL '140 days'),
('Umar Siddiqui',      'umar.siddiqui@email.com',      'Pakistan',       NOW() - INTERVAL '130 days'),
('Valentina Cruz',     'valentina.cruz@email.com',     'Colombia',       NOW() - INTERVAL '120 days'),
('William Turner',     'william.turner@email.com',     'Australia',      NOW() - INTERVAL '110 days'),
('Xin Li',             'xin.li@email.com',             'China',          NOW() - INTERVAL '100 days'),
('Yuki Tanaka',        'yuki.tanaka@email.com',        'Japan',          NOW() - INTERVAL '90 days'),
('Zara Patel',         'zara.patel@email.com',         'India',          NOW() - INTERVAL '85 days'),
('Aaron Brooks',       'aaron.brooks@email.com',       'United States',  NOW() - INTERVAL '80 days'),
('Bianca Marques',     'bianca.marques@email.com',     'Brazil',         NOW() - INTERVAL '75 days'),
('Carlos Mendez',      'carlos.mendez@email.com',      'Argentina',      NOW() - INTERVAL '70 days'),
('Diana Park',         'diana.park@email.com',         'South Korea',    NOW() - INTERVAL '65 days'),
('Ethan Walker',       'ethan.walker@email.com',       'Canada',         NOW() - INTERVAL '60 days'),
('Fiona Campbell',     'fiona.campbell@email.com',     'Scotland',       NOW() - INTERVAL '55 days'),
('Gabriel Moreau',     'gabriel.moreau@email.com',     'France',         NOW() - INTERVAL '50 days'),
('Helen Zhou',         'helen.zhou@email.com',         'China',          NOW() - INTERVAL '45 days'),
('Igor Sokolov',       'igor.sokolov@email.com',       'Ukraine',        NOW() - INTERVAL '40 days'),
('Jasmine Wright',     'jasmine.wright@email.com',     'United States',  NOW() - INTERVAL '35 days'),
('Kenji Yamamoto',     'kenji.yamamoto@email.com',     'Japan',          NOW() - INTERVAL '30 days'),
('Lena Hoffmann',      'lena.hoffmann@email.com',      'Germany',        NOW() - INTERVAL '25 days'),
('Marco Bianchi',      'marco.bianchi@email.com',      'Italy',          NOW() - INTERVAL '20 days'),
('Nina Johansson',     'nina.johansson@email.com',     'Sweden',         NOW() - INTERVAL '15 days'),
('Omar Abdullah',      'omar.abdullah@email.com',      'Jordan',         NOW() - INTERVAL '12 days'),
('Paula Gomes',        'paula.gomes@email.com',        'Brazil',         NOW() - INTERVAL '10 days'),
('Raj Nair',           'raj.nair@email.com',           'India',          NOW() - INTERVAL '8 days'),
('Sofia Andersen',     'sofia.andersen@email.com',     'Denmark',        NOW() - INTERVAL '6 days'),
('Tom Hughes',         'tom.hughes@email.com',         'United Kingdom', NOW() - INTERVAL '4 days'),
('Uma Krishnan',       'uma.krishnan@email.com',       'India',          NOW() - INTERVAL '3 days'),
('Victor Larsson',     'victor.larsson@email.com',     'Norway',         NOW() - INTERVAL '2 days'),
('Wendy Chang',        'wendy.chang@email.com',        'Taiwan',         NOW() - INTERVAL '1 day'),
('Xavier Dupont',      'xavier.dupont@email.com',      'Belgium',        NOW() - INTERVAL '12 hours'),
('Yara Hassan',        'yara.hassan@email.com',        'Egypt',          NOW() - INTERVAL '6 hours');

-- -------------------------------------------------------
-- 2. Products (30 rows)
-- -------------------------------------------------------
INSERT INTO products (name, category, price, stock_qty) VALUES
('Wireless Noise-Cancelling Headphones', 'Electronics',  299.99,  150),
('Mechanical Keyboard RGB',              'Electronics',  129.99,  200),
('4K Ultra HD Monitor 27"',             'Electronics',  449.99,   80),
('Ergonomic Office Chair',              'Furniture',    399.00,   60),
('Standing Desk Adjustable',            'Furniture',    599.00,   45),
('Yoga Mat Premium',                    'Sports',        49.99,  300),
('Running Shoes Pro',                   'Sports',       119.99,  180),
('Smart Water Bottle',                  'Sports',        34.99,  250),
('Coffee Maker Deluxe',                 'Kitchen',       89.99,  120),
('Air Fryer XL 6Qt',                   'Kitchen',       99.99,  140),
('Instant Pot 7-in-1',                 'Kitchen',       79.99,  160),
('Bamboo Cutting Board Set',            'Kitchen',       29.99,  400),
('Python Programming Book',             'Books',         39.99,  500),
('Data Science Handbook',              'Books',         44.99,  350),
('The Lean Startup',                   'Books',         18.99,  600),
('Atomic Habits',                      'Books',         16.99,  700),
('Wireless Charging Pad',              'Electronics',   29.99,  300),
('USB-C Hub 7-in-1',                   'Electronics',   49.99,  220),
('Bluetooth Speaker Portable',         'Electronics',   79.99,  175),
('Smart LED Desk Lamp',                'Electronics',   59.99,  190),
('Resistance Bands Set',               'Sports',        24.99,  350),
('Foam Roller Recovery',               'Sports',        22.99,  280),
('Protein Powder Chocolate',           'Health',        54.99,  200),
('Multivitamin Daily Pack',            'Health',        29.99,  450),
('Essential Oil Diffuser',             'Home',          39.99,  220),
('Scented Candle Set',                 'Home',          24.99,  380),
('Laptop Backpack 15"',               'Accessories',   69.99,  160),
('Leather Wallet RFID',               'Accessories',   34.99,  300),
('Sunglasses UV400',                  'Accessories',   59.99,  200),
('Stainless Steel Thermos',           'Kitchen',       27.99,  320);

-- -------------------------------------------------------
-- 3. Orders (120 rows spread across 12 months)
-- -------------------------------------------------------
INSERT INTO orders (user_id, product_id, quantity, total_amount, status, created_at) VALUES
(1,  1, 1,  299.99, 'delivered',   NOW() - INTERVAL '350 days'),
(2,  9, 2,  179.98, 'delivered',   NOW() - INTERVAL '330 days'),
(3, 13, 1,   39.99, 'delivered',   NOW() - INTERVAL '315 days'),
(4,  2, 1,  129.99, 'delivered',   NOW() - INTERVAL '310 days'),
(5,  7, 2,  239.98, 'delivered',   NOW() - INTERVAL '305 days'),
(6,  4, 1,  399.00, 'delivered',   NOW() - INTERVAL '295 days'),
(7,  3, 1,  449.99, 'delivered',   NOW() - INTERVAL '285 days'),
(8, 19, 1,   79.99, 'delivered',   NOW() - INTERVAL '275 days'),
(9, 15, 3,   56.97, 'delivered',   NOW() - INTERVAL '265 days'),
(10,10, 1,   99.99, 'delivered',   NOW() - INTERVAL '255 days'),
(11, 6, 2,   99.98, 'delivered',   NOW() - INTERVAL '245 days'),
(12,14, 1,   44.99, 'delivered',   NOW() - INTERVAL '235 days'),
(13, 5, 1,  599.00, 'delivered',   NOW() - INTERVAL '225 days'),
(14,11, 2,  159.98, 'delivered',   NOW() - INTERVAL '215 days'),
(15,16, 4,   67.96, 'delivered',   NOW() - INTERVAL '205 days'),
(16, 1, 1,  299.99, 'delivered',   NOW() - INTERVAL '195 days'),
(17,20, 1,   59.99, 'delivered',   NOW() - INTERVAL '185 days'),
(18,28, 2,   69.98, 'delivered',   NOW() - INTERVAL '175 days'),
(19, 8, 3,  104.97, 'delivered',   NOW() - INTERVAL '165 days'),
(20,17, 2,   59.98, 'delivered',   NOW() - INTERVAL '155 days'),
(21,23, 1,   54.99, 'delivered',   NOW() - INTERVAL '145 days'),
(22, 2, 1,  129.99, 'delivered',   NOW() - INTERVAL '135 days'),
(23,12, 2,   59.98, 'delivered',   NOW() - INTERVAL '125 days'),
(24, 3, 1,  449.99, 'delivered',   NOW() - INTERVAL '115 days'),
(25,18, 1,   49.99, 'delivered',   NOW() - INTERVAL '105 days'),
(26, 9, 1,   89.99, 'shipped',     NOW() - INTERVAL '95 days'),
(27, 4, 1,  399.00, 'delivered',   NOW() - INTERVAL '85 days'),
(28,24, 3,   89.97, 'delivered',   NOW() - INTERVAL '75 days'),
(29,19, 2,  159.98, 'delivered',   NOW() - INTERVAL '65 days'),
(30,13, 2,   79.98, 'delivered',   NOW() - INTERVAL '55 days'),
(31, 7, 1,  119.99, 'shipped',     NOW() - INTERVAL '50 days'),
(32, 6, 3,  149.97, 'delivered',   NOW() - INTERVAL '48 days'),
(33,10, 2,  199.98, 'delivered',   NOW() - INTERVAL '46 days'),
(34,21, 2,   49.98, 'delivered',   NOW() - INTERVAL '44 days'),
(35,22, 1,   22.99, 'delivered',   NOW() - INTERVAL '42 days'),
(36,15, 2,   37.98, 'processing',  NOW() - INTERVAL '40 days'),
(37,16, 5,   84.95, 'delivered',   NOW() - INTERVAL '38 days'),
(38,11, 1,   79.99, 'delivered',   NOW() - INTERVAL '36 days'),
(39, 5, 1,  599.00, 'shipped',     NOW() - INTERVAL '34 days'),
(40,20, 2,  119.98, 'delivered',   NOW() - INTERVAL '32 days'),
(41, 1, 2,  599.98, 'delivered',   NOW() - INTERVAL '30 days'),
(42,17, 3,   89.97, 'delivered',   NOW() - INTERVAL '28 days'),
(43,14, 2,   89.98, 'delivered',   NOW() - INTERVAL '26 days'),
(44, 8, 4,  139.96, 'delivered',   NOW() - INTERVAL '24 days'),
(45,25, 2,   79.98, 'processing',  NOW() - INTERVAL '22 days'),
(46,26, 3,   74.97, 'delivered',   NOW() - INTERVAL '20 days'),
(47, 2, 2,  259.98, 'delivered',   NOW() - INTERVAL '18 days'),
(48,29, 1,   59.99, 'shipped',     NOW() - INTERVAL '16 days'),
(49, 3, 1,  449.99, 'processing',  NOW() - INTERVAL '14 days'),
(50,30, 2,   55.98, 'delivered',   NOW() - INTERVAL '12 days'),
(1,  9, 1,   89.99, 'delivered',   NOW() - INTERVAL '11 days'),
(3, 18, 2,   99.98, 'delivered',   NOW() - INTERVAL '10 days'),
(5, 23, 1,   54.99, 'pending',     NOW() - INTERVAL '9 days'),
(7, 12, 3,   89.97, 'delivered',   NOW() - INTERVAL '8 days'),
(9, 28, 1,   34.99, 'shipped',     NOW() - INTERVAL '7 days'),
(11,19, 2,  159.98, 'delivered',   NOW() - INTERVAL '6 days'),
(13, 4, 1,  399.00, 'pending',     NOW() - INTERVAL '5 days'),
(15, 7, 1,  119.99, 'processing',  NOW() - INTERVAL '4 days'),
(17, 1, 1,  299.99, 'shipped',     NOW() - INTERVAL '3 days'),
(19,10, 1,   99.99, 'pending',     NOW() - INTERVAL '2 days'),
(21,13, 1,   39.99, 'pending',     NOW() - INTERVAL '1 day'),
(23,16, 2,   33.98, 'pending',     NOW() - INTERVAL '12 hours'),
(25, 6, 2,   99.98, 'pending',     NOW() - INTERVAL '6 hours'),
(27,15, 3,   56.97, 'pending',     NOW() - INTERVAL '3 hours'),
(29,21, 2,   49.98, 'pending',     NOW() - INTERVAL '1 hour'),
(2, 20, 1,   59.99, 'cancelled',   NOW() - INTERVAL '100 days'),
(4, 22, 1,   22.99, 'cancelled',   NOW() - INTERVAL '90 days'),
(6, 26, 2,   49.98, 'cancelled',   NOW() - INTERVAL '80 days'),
(8, 24, 1,   29.99, 'cancelled',   NOW() - INTERVAL '70 days'),
(10,25, 3,  119.97, 'cancelled',   NOW() - INTERVAL '60 days'),
(12,27, 1,   69.99, 'cancelled',   NOW() - INTERVAL '50 days'),
(14,29, 2,  119.98, 'cancelled',   NOW() - INTERVAL '40 days'),
(16,30, 1,   27.99, 'cancelled',   NOW() - INTERVAL '30 days'),
(18, 2, 1,  129.99, 'delivered',   NOW() - INTERVAL '180 days'),
(20, 5, 1,  599.00, 'delivered',   NOW() - INTERVAL '170 days'),
(22, 7, 2,  239.98, 'delivered',   NOW() - INTERVAL '160 days'),
(24, 9, 1,   89.99, 'delivered',   NOW() - INTERVAL '150 days'),
(26,11, 3,  239.97, 'delivered',   NOW() - INTERVAL '140 days'),
(28,13, 2,   79.98, 'delivered',   NOW() - INTERVAL '130 days'),
(30,15, 4,   75.96, 'delivered',   NOW() - INTERVAL '120 days'),
(32,17, 2,   59.98, 'delivered',   NOW() - INTERVAL '110 days'),
(34,19, 1,   79.99, 'delivered',   NOW() - INTERVAL '100 days'),
(36,21, 3,   74.97, 'delivered',   NOW() - INTERVAL '90 days'),
(38,23, 2,  109.98, 'delivered',   NOW() - INTERVAL '80 days'),
(40,25, 1,   39.99, 'delivered',   NOW() - INTERVAL '70 days'),
(42,27, 2,  139.98, 'delivered',   NOW() - INTERVAL '60 days'),
(44,29, 1,   59.99, 'delivered',   NOW() - INTERVAL '50 days'),
(46, 1, 1,  299.99, 'delivered',   NOW() - INTERVAL '45 days'),
(48, 3, 1,  449.99, 'delivered',   NOW() - INTERVAL '40 days'),
(50, 5, 1,  599.00, 'delivered',   NOW() - INTERVAL '35 days'),
(1,  2, 2,  259.98, 'delivered',   NOW() - INTERVAL '25 days'),
(5,  4, 1,  399.00, 'delivered',   NOW() - INTERVAL '22 days'),
(10, 6, 2,   99.98, 'delivered',   NOW() - INTERVAL '19 days'),
(15, 8, 3,  104.97, 'delivered',   NOW() - INTERVAL '17 days'),
(20,10, 1,   99.99, 'delivered',   NOW() - INTERVAL '15 days'),
(25,12, 4,  119.96, 'delivered',   NOW() - INTERVAL '13 days'),
(30,14, 2,   89.98, 'delivered',   NOW() - INTERVAL '11 days'),
(35,16, 3,   50.97, 'delivered',   NOW() - INTERVAL '9 days'),
(40,18, 1,   49.99, 'shipped',     NOW() - INTERVAL '7 days'),
(45,20, 2,  119.98, 'shipped',     NOW() - INTERVAL '5 days'),
(50,22, 1,   22.99, 'processing',  NOW() - INTERVAL '3 days'),
(3,  1, 1,  299.99, 'processing',  NOW() - INTERVAL '2 days'),
(7,  3, 1,  449.99, 'pending',     NOW() - INTERVAL '1 day'),
(11, 5, 1,  599.00, 'pending',     NOW() - INTERVAL '10 hours'),
(16, 7, 2,  239.98, 'pending',     NOW() - INTERVAL '5 hours'),
(22, 9, 1,   89.99, 'pending',     NOW() - INTERVAL '2 hours'),
(28,11, 2,  159.98, 'pending',     NOW() - INTERVAL '30 minutes'),
(33,28, 3,  104.97, 'delivered',   NOW() - INTERVAL '120 days'),
(39,30, 2,   55.98, 'delivered',   NOW() - INTERVAL '110 days'),
(41,24, 1,   29.99, 'delivered',   NOW() - INTERVAL '105 days'),
(43,26, 4,   99.96, 'delivered',   NOW() - INTERVAL '95 days'),
(47,17, 2,   59.98, 'delivered',   NOW() - INTERVAL '88 days'),
(49,21, 3,   74.97, 'delivered',   NOW() - INTERVAL '78 days'),
(2,  3, 1,  449.99, 'delivered',   NOW() - INTERVAL '68 days'),
(8, 14, 2,   89.98, 'delivered',   NOW() - INTERVAL '58 days'),
(14,23, 1,   54.99, 'delivered',   NOW() - INTERVAL '48 days'),
(20,29, 2,  119.98, 'delivered',   NOW() - INTERVAL '38 days'),
(26,16, 6,  101.94, 'delivered',   NOW() - INTERVAL '28 days'),
(32,25, 2,   79.98, 'delivered',   NOW() - INTERVAL '18 days'),
(38,27, 1,   69.99, 'shipped',     NOW() - INTERVAL '8 days'),
(44,30, 3,   83.97, 'pending',     NOW() - INTERVAL '4 days');

-- -------------------------------------------------------
-- 4. Subscriptions (50 rows)
-- -------------------------------------------------------
INSERT INTO subscriptions (user_id, plan, status, started_at, renewed_at) VALUES
(1,  'pro',        'active',    NOW() - INTERVAL '300 days', NOW() - INTERVAL '30 days'),
(2,  'basic',      'active',    NOW() - INTERVAL '280 days', NOW() - INTERVAL '10 days'),
(3,  'enterprise', 'active',    NOW() - INTERVAL '260 days', NOW() - INTERVAL '20 days'),
(4,  'free',       'active',    NOW() - INTERVAL '240 days', NULL),
(5,  'pro',        'active',    NOW() - INTERVAL '220 days', NOW() - INTERVAL '25 days'),
(6,  'basic',      'cancelled', NOW() - INTERVAL '200 days', NOW() - INTERVAL '170 days'),
(7,  'enterprise', 'active',    NOW() - INTERVAL '180 days', NOW() - INTERVAL '15 days'),
(8,  'free',       'active',    NOW() - INTERVAL '160 days', NULL),
(9,  'pro',        'active',    NOW() - INTERVAL '140 days', NOW() - INTERVAL '20 days'),
(10, 'basic',      'expired',   NOW() - INTERVAL '130 days', NOW() - INTERVAL '100 days'),
(11, 'enterprise', 'active',    NOW() - INTERVAL '120 days', NOW() - INTERVAL '10 days'),
(12, 'pro',        'active',    NOW() - INTERVAL '110 days', NOW() - INTERVAL '5 days'),
(13, 'free',       'active',    NOW() - INTERVAL '100 days', NULL),
(14, 'basic',      'active',    NOW() - INTERVAL '90 days',  NOW() - INTERVAL '5 days'),
(15, 'pro',        'cancelled', NOW() - INTERVAL '80 days',  NOW() - INTERVAL '60 days'),
(16, 'enterprise', 'active',    NOW() - INTERVAL '75 days',  NOW() - INTERVAL '15 days'),
(17, 'free',       'active',    NOW() - INTERVAL '70 days',  NULL),
(18, 'basic',      'active',    NOW() - INTERVAL '65 days',  NOW() - INTERVAL '5 days'),
(19, 'pro',        'active',    NOW() - INTERVAL '60 days',  NOW() - INTERVAL '1 day'),
(20, 'enterprise', 'trial',     NOW() - INTERVAL '55 days',  NULL),
(21, 'free',       'active',    NOW() - INTERVAL '50 days',  NULL),
(22, 'pro',        'active',    NOW() - INTERVAL '45 days',  NOW() - INTERVAL '15 days'),
(23, 'basic',      'active',    NOW() - INTERVAL '40 days',  NOW() - INTERVAL '10 days'),
(24, 'enterprise', 'active',    NOW() - INTERVAL '35 days',  NOW() - INTERVAL '5 days'),
(25, 'free',       'active',    NOW() - INTERVAL '30 days',  NULL),
(26, 'pro',        'active',    NOW() - INTERVAL '28 days',  NULL),
(27, 'basic',      'active',    NOW() - INTERVAL '25 days',  NULL),
(28, 'enterprise', 'trial',     NOW() - INTERVAL '20 days',  NULL),
(29, 'free',       'active',    NOW() - INTERVAL '18 days',  NULL),
(30, 'pro',        'active',    NOW() - INTERVAL '15 days',  NULL),
(31, 'basic',      'active',    NOW() - INTERVAL '12 days',  NULL),
(32, 'enterprise', 'active',    NOW() - INTERVAL '10 days',  NULL),
(33, 'free',       'active',    NOW() - INTERVAL '8 days',   NULL),
(34, 'pro',        'trial',     NOW() - INTERVAL '6 days',   NULL),
(35, 'basic',      'active',    NOW() - INTERVAL '5 days',   NULL),
(36, 'enterprise', 'active',    NOW() - INTERVAL '4 days',   NULL),
(37, 'free',       'active',    NOW() - INTERVAL '3 days',   NULL),
(38, 'pro',        'active',    NOW() - INTERVAL '2 days',   NULL),
(39, 'basic',      'active',    NOW() - INTERVAL '1 day',    NULL),
(40, 'enterprise', 'active',    NOW() - INTERVAL '20 hours', NULL),
(41, 'free',       'active',    NOW() - INTERVAL '15 hours', NULL),
(42, 'pro',        'active',    NOW() - INTERVAL '10 hours', NULL),
(43, 'basic',      'cancelled', NOW() - INTERVAL '50 days',  NOW() - INTERVAL '20 days'),
(44, 'enterprise', 'active',    NOW() - INTERVAL '8 hours',  NULL),
(45, 'free',       'active',    NOW() - INTERVAL '5 hours',  NULL),
(46, 'pro',        'active',    NOW() - INTERVAL '3 hours',  NULL),
(47, 'basic',      'active',    NOW() - INTERVAL '2 hours',  NULL),
(48, 'enterprise', 'trial',     NOW() - INTERVAL '1 hour',   NULL),
(49, 'free',       'active',    NOW() - INTERVAL '30 minutes', NULL),
(50, 'pro',        'active',    NOW() - INTERVAL '10 minutes', NULL);

SELECT 'Seeding complete.' AS status;
SELECT 'users' AS tbl, COUNT(*) FROM users
UNION ALL SELECT 'products', COUNT(*) FROM products
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'subscriptions', COUNT(*) FROM subscriptions;
